### PR TITLE
Bakafa api

### PR DESCRIPTION
**Pull request by MoeZilla**

### CODE REVIEW

**Comment by ArshCypherZ** [comment]
looks cool

**Comment by MoeZilla** [comment]
Toh yeha kaise abe

**Comment by MoeZilla** [comment]
Arsh itna GitHub mat use karo

**Comment by MoeZilla** [comment]
> looks cool

Chal jhuta

**Comment by ArshCypherZ** [comment]
bakufu hota h voh, 

tu hi toh bola tha ki coder banja
toh m bangya

**Comment by ArshCypherZ** [comment]
aur bta kia chlra teri zindagi m

**Comment by MoeZilla** [comment]
> aur bta kia chlra teri zindagi m

Teri girlfriend

**Comment by ArshCypherZ** [comment]
voh toh chodhkr chali gayi mjhe 4 mahine phle

**Comment by MoeZilla** [comment]
Ex chal gyi mujhe

**Pull request merged**
